name: Manual Deploy

on:
  # Manual trigger from the "Actions" tab on the GitHub UI.
  workflow_dispatch:
    inputs:
      deploy_target:
        description: 'Deploy target'
        required: true
        default: 'production'
        type: choice
        options:
          - production
          - any-other-deploy-target-branches

jobs:
  deploy:
    uses: ./.github/workflows/deploy-pr.yml
    with:
      deploy_target: ${{ github.event.inputs.deploy_target }}
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN_YOUR_BOT }}